apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: cloudflare-tunnel-secret
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: cloudflare-tunnel-token
