
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudflared
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: flux-system
  values:
    replicaCount: 2
    cloudflare:
      tunnelTokenSecretName: cloudflared-token
