apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflared
resources:
  - namespace.yaml
  - cloudflared-token.enc.yaml
  - values-configmap.yaml
  - helm-repository.yaml
  - helmrelease.yaml
