apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-tunnel-config
  namespace: cloudflare
data:
  config.yaml: |
    ingress:
      - hostname: "linkding.andrzejsidor.online"
        service: http://linkding.linkding.svc.cluster.local:9090
      - hostname: "*.andrzejsidor.online"
        service: http://traefik.traefik.svc.cluster.local:9000
      - service: http_status:404
