apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infra/Cert-Manager
  # - infra/Certificates  # DEPLOY PO zainstalowaniu Cert Manager
  - infra/ESO
  - infra/Traefik
  - infra/Certificate
  # - apps/demo1
  # - apps/demo2
