apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - k8s/infra/Cert-Manager
  - k8s/infra/Certificates
  - k8s/infra/Cloudflare
  - k8s/infra/ESO
  - k8s/infra/Prometheus
  - k8s/infra/Loki
  - k8s/infra/Longhorn

  - k8s/infra/MetalLB
  - k8s/apps/linkding
  - k8s/apps/grafana

