apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: prometheus
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '58.*'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: prometheus
  values:
    prometheus:
      prometheusSpec:
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1024Mi
        retention: 30d
        storageSpec:
          emptyDir: {}

    grafana:
      enabled: false

    alertmanager:
      enabled: true
      alertmanagerSpec:
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

    nodeExporter:
      enabled: true

    kubeStateMetrics:
      enabled: true

    prometheus-node-exporter:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
