apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gsm-demo-store
  namespace: demo
spec:
  provider:
    gcpsm:
      projectID: mysecret-476812
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: demo-secrets-sa
