---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcp-demo-secret
  namespace: demo2
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: gcpsm-cluster-store
    kind: ClusterSecretStore
  target:
    name: demo-app-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        API_KEY: "{{ .apikey }}"
        DATABASE_URL: "{{ .dburl }}"
  data:
  - secretKey: apikey
    remoteRef:
      key: demo-api-key
  - secretKey: dburl
    remoteRef:
      key: demo-database-url
