apiVersion: v1
kind: Service
metadata:
  name: headlamp-loadbalancer
  namespace: headlamp
  labels:
    app.kubernetes.io/name: headlamp
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 4466
      protocol: TCP
    - name: https
      port: 443
      targetPort: 4466
      protocol: TCP
  selector:
    app.kubernetes.io/name: headlamp
