apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weave-gitops-auth
  namespace: weave-gitops
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: cluster-user-auth
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: weave-gitops-username
    - secretKey: password
      remoteRef:
        key: weave-gitops-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weave-gitops-admin-password
  namespace: weave-gitops
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: weave-gitops-admin-password
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: weave-gitops-username
    - secretKey: password
      remoteRef:
        key: weave-gitops-password
