apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: weave-gitops
  namespace: weave-gitops
spec:
  interval: 5m
  url: https://github.com/weaveworks/weave-gitops
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include deploy dir
    !/charts
