apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero-gcp-credentials
  namespace: velero
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: velero-gcp-credentials
    creationPolicy: Owner
  data:
    - secretKey: cloud
      remoteRef:
        key: velero-gcp-sa
