apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wallabag-db-credentials
  namespace: wallabag
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: wallabag-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: wallabag-username
    - secretKey: password
      remoteRef:
        key: wallabag-password
    - secretKey: database
      remoteRef:
        key: wallabag-database
