---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcpsm-cluster-store
spec:
  provider:
    gcpsm:
      projectID: "mysecret-476812"
      auth:
        secretRef:
          secretAccessKey:
            name: gcp-credentials
            namespace: external-secrets
            key: secret-access-credentials
