---
# Przykład użycia External Secret - pobiera sekret z Google Secret Manager
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcp-secret-example
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-secret-store
    kind: SecretStore
  target:
    name: gcp-secret-example
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: my-secret-name
      property: username
  - secretKey: password
    remoteRef:
      key: my-secret-name
      property: password
