apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- helm-repo.yaml
- helm-release.yaml
- serviceaccount.yaml
- rbac.yaml
- secret-store.yaml
- cluster-secret-store.yaml
- example-external-secret.yaml
