# clusters/base/eso/secretstore.yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-store
  namespace: demo
spec:
  provider:
    gcpsm:
      projectID: mysecret-476812