---
# ClusterSecretStore dla Google Secret Manager
# Ten SecretStore jest dostępny dla wszystkich namespace'ów w klastrze
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcpsm-cluster-secret-store
spec:
  provider:
    gcpsm:
      projectID: "mysecret-476812"  # Zmień na swój Project ID
      auth:
        secretRef:
          secretAccessKey:
            name: gcp-credentials
            namespace: external-secrets
            key: secret-access-credentials

---
# Alternatywnie: SecretStore dla konkretnego namespace'u
# Odkomentuj poniżej jeśli chcesz SecretStore zamiast ClusterSecretStore
# apiVersion: external-secrets.io/v1beta1
# kind: SecretStore
# metadata:
#   name: gcpsm-secret-store
#   namespace: default
# spec:
#   provider:
#     gcpsm:
#       projectID: "mysecret-476812"  # Zmień na swój Project ID
#       auth:
#         secretRef:
#           secretAccessKey:
#             name: gcp-credentials
#             namespace: external-secrets
#             key: secret-access-credentials
