---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcpsm-secret-store
  namespace: external-secrets
spec:
  provider:
    gcpsm:
      projectID: "mysecret-476812"
      auth:
        secretRef:
          secretAccessKey:
            name: gcp-credentials
            key: secret-access-credentials
