apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: every-6-hours
  namespace: velero
spec:
  schedule: "0 */6 * * *"
  template:
    includedNamespaces:
      - "*"
    includeClusterResources: true
    storageLocation: default
    ttl: 24h0m0s
