apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backup-schedule.yaml
  - backup-size-exporter.yaml

labels:
  - pairs:
      app.kubernetes.io/name: velero
      app.kubernetes.io/component: backup
    includeSelectors: true
